
PATCH http://localhost:3333/chat/1
Content-Type: application/json

{
    "room": 100
}

###
GET http://localhost:3333/chat


####
POST http://localhost:3333/subject
Content-Type: application/json

{
    "chat": 1,
    "name": "oi",
    "slug": "oi"
}